# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: jupyterlab-launchpad
  version: "1.0.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/jupyterlab_launchpad-${{ version }}.tar.gz
  sha256: ade9f313c0f4a5ddee6804c4a6af3baf4be968f82aa9c1e6085b72b9038b8099

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - jupyter_server >=2.0.1,<3

tests:
  - python:
      imports:
        - jupyterlab_launchpad
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A redesigned JupyterLab launcher
  homepage: https://github.com/nebari-dev/jupyterlab-launchpad
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - style/icons/md/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
